version: 2
project_name: oks

before:
  hooks:
    - go mod tidy

builds:
  - id: oks
    main: .
    binary: oks
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    ids:
      - oks
    name_template: "oks_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: zip

checksum:
  name_template: "checksums.txt"

release:
  draft: false
  prerelease: "auto"
